### PR TITLE
add DigiStump Oak board

### PR DESCRIPTION
**Pull request by boneskull**
here's another try at this.   they've more-or-less dropped Particle support, so now it's just a plain ol' ESP8266 board.

please let me know if I need to retarget this PR to a diff branch; that wasn't clear.

### CODE REVIEW

**Comment by boneskull** [comment]
[PR in esp8266/Arduino](https://github.com/esp8266/Arduino/pull/3515)

**Comment by boneskull** [comment]
Given there's 100+ outstanding PRs on [esp8266/Arduino](/esp8266/Arduino), I'm dubious this will get merged any time soon.

**Comment by boneskull** [comment]
@ivankravets I'm wondering what's the most straightforward way to use my changes with PlatformIO?  I have struggled with this.  I know I can install stuff from a URL, but it looks as if the platform must be modified to use the framework...

**Comment by ivankravets** [comment]
Thanks a lot for PR. Please re-test with http://docs.platformio.org/page/platforms/espressif8266.html#using-arduino-framework-with-staging-version

**Pull request merged**
