### PR TITLE
Added esp8266-nonos-sdk framework

### PR DESCRIPTION
**Pull request by sanderv32**
This PR adds EspressIf NONOS SDK to platform

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks!!! Could you provide some example to `examples` folder?
See `examples` in a root of repo.

**Comment by sanderv32** [comment]
Made it WIP because still have to modify `main.py` in the builder directory.

**Comment by sanderv32** [comment]
Removed WIP as example is working on a ESP8266-12E board and also had to change the loadaddress to 0x10000.

**Comment by ivankravets** [comment]
@sanderv32 could you help us with https://community.platformio.org/t/using-plaformio-with-esp-nonos-sdk/6774?

**Comment by sanderv32** [comment]
@ivankravets I can help, but i first need to getting my ESP kit working again. It seems that i have the same problem as described in your link but then with the Arduino kit :-(

**Comment by ivankravets** [comment]
Thanks!!!

**Comment by iivancev** [comment]
whats the status with this?

**Comment by sanderv32** [comment]
Yesterday I confirmed I will help but I have to do this in my spare time, so you need to be a little more patience.

**Pull request merged**
